
binary_sensor:
  ############################################################################
  # Movement
  - platform: gpio
    pin: GPIO2
    name: "Movement"
    device_class: motion
    filters:
      - delayed_off: ${delay}
    on_press:
      if:
        condition:
          switch.is_on: use_lights
        then:
          - light.turn_on:
              id: onboard_led
              red: 0%
              green: 50%
              blue: 0%
    on_release:
    #  - light.turn_off: onboard_led
      - light.turn_on:
          id: onboard_led
          red: 3%
          green: 0%
          blue: 0%
