
binary_sensor:
  ############################################################################
  # Movement
  - platform: gpio
    pin: GPIO2
    name: "Movement"
    device_class: motion
    filters:
      #- delayed_off: ${delay}
      - delayed_off: 2s
    on_press:
      if:
        condition:
          switch.is_on: use_lights
        then:
          - output.turn_on: LED1
          - output.turn_off: LED2
#          - light.turn_on:
#              id: onboard_led
#              red: 0%
#              green: 50%
#              blue: 0%
    on_release:
      - output.turn_on: LED2
      - output.turn_off: LED1
#      - light.turn_on:
#          id: onboard_led
#          red: 3%
#          green: 0%
#          blue: 0%
