############################################################################
uart:
  id: ld2420_uart
  tx_pin: GPIO3
  rx_pin: GPIO2
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

binary_sensor:
############################################################################
  - platform: ld2420
    has_target:
      name: Presence
      on_press:
        then:
          if:
            condition:
              switch.is_on: use_lights
            then:
            - light.turn_on:
                id: onboard_led
                red: 0%
                green: 50%
                blue: 0%
      on_release:
        then:
          - light.turn_off:
              id: onboard_led
sensor:
############################################################################
  - platform: ld2420
    moving_distance:
      name : Moving Distance
      filters:
        - clamp:
            max_value: 800
            ignore_out_of_range: true
            
button:
############################################################################
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode
      
number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    
    gate_move_sensitivity:
      name: Move Calibration Sensitivity Factor
    gate_still_sensitivity:
      name: Still Calibration Sensitivity Factor
    
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value
